c:\tc\lib\c0l+ship+base+board+comets+command+buysell+destruct+distrib+extend+findgo+help+info+input+leave+long+mail+name+names+peace+phaser+plague+power+protect+remote+rpt+scan+spy+stand+stat+sysop+taxes+time+torp+warp+close+free+random+fileio+ping+quit+sled+auction+nav+color+cops+goals+leash+scout+async+maydrop
ship.exe

c:\tc\lib\emu.lib+c:\tc\lib\mathl.lib+c:\tc\lib\cl.lib+c:\tc\lib\fp87.lib

